### PR TITLE
Create GeometryCollection for relations with mixed member types (fixes #3)

### LINKED ISSUE #3: Relations with LineString and Polygon members have no geometry
If a relation has Polygons and LineStrings way members, the resulting feature has no geometry.

tyrasd/osmtogeojson instead seems to export every member as feature with an @relations property.

osmtogeojson should either behave accordingly or provide all members geometries as a GeometryCollection.

Example for [relation/5576903](https://openstreetmap.org/relation/5576903):
```
{
      "type": "Feature",
      "properties": {
        "@id": "way/376770457",
        "covered": "yes",
        "highway": "service",
        "indoor": "yes",
        "layer": "-2",
        "location": "underground",
        "oneway": "yes",
        "ref": "Ebene B",
        "service": "parking_aisle",
        "sidewalk": "left",
        "@relations": [
          {
            "role": "",
            "rel": 5576903,
            "reltags": {
              "amenity": "parking",
              "fee": "yes",
              "name": "Schillerplatz",
              "opening_hours": "24/7",
              "operator": "APCOA PARKING Deutschland GmbH",
              "parking": "underground",
              "site": "parking",
              "type": "site",
              "url": "https://service.stuttgart.de/lhs-services/ivlz/index.php?uid=35&objectid=108523&objecttype=dept&page=svc&servicetype=parking&serviceid=9356&detailid=65&showservice=1",
              "website": "https://www.apcoa.de/parken-in/stuttgart/schillerplatz.html"
            }
          }
        ]
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              9.178458,
              48.7770338
            ],
           ...
          ]]
      }
    }
```

### PR DESCRIPTION
**Pull request by hbruch**
If a relation has way and area members, this PR will export them as GeometryCollection with LineString/Polygon geometries.

Nodes are added as Point to these GeometryCollection as well.

However, for relations which have nodes and ways/areas, the original behavior is retained, so these nodes will still not be exported.

Members of type 'relation' are not handled yet. For these, a warning is logged.

### CODE REVIEW

**Comment by tommyjcarpenter** [comment]
@hbruch the unit test is failing (not the last failure, that was preexisting, and relates to winding order): tests/test_conversion.py::ConversionTest::test_relation_with_different_member_types_becomes_GeometryCollection FAILED. 

Can you please have a look?

**Comment by tommyjcarpenter** [comment]
I really should learn Travis and set up tox to run here... but for now I just ran tox locally.

**Comment by hbruch** [comment]
Is this the output you are seeing?:

```
E   -                'properties': {'amenity': 'parking',
E   ?                                ^^^^ ^^    ^ ^^  ^
E
E   +                'properties': {'@id': 'relation/5576903',
E   ?                                ^ ^    ^^^ ^ + ^^^^^^^^
E
E   +                               'amenity': 'parking',
E                                   'fee': 'yes',
E   -                               'id': 'relation/5576903',
```

If you are running the test on branch issue_3, it fails, on master with #7 merged before, it should pass.

Can you confirm or provide the error message you get?

**Comment by tommyjcarpenter** [comment]
ah yes, you are correct.

**Comment by tommyjcarpenter** [comment]
please bump the version, maybe 0.1.0, then I'll merge & push

**Comment by hbruch** [comment]
I merged master and changed the version to 0.0.2. Not sure about semantic versioning. Is the resulting GeoJSON part of API? I think not (at least not now in 0.x.x), so I added a comment to the ChangeLog.
The test should pass now also.

**Comment by hbruch** [comment]
@tommyjcarpenter Thanks! Would you mind pushing 0.0.2 to PyPi?

**Comment by tommyjcarpenter** [comment]
@hbruch done

**Pull request merged**
